project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.core.urls'))
]

applications/core/models.py
import uuid, random
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator
from django.forms import ValidationError
from applications.mapping.models import Provinsi, KabupatenKota, Kecamatan, KelurahanDesa
# from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone

# Create your models here.
class Warehouse(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # Unique identifier
    code = models.CharField(max_length=20, unique=True)  # unique=True memastikan bahwa tidak ada dua entri
    name = models.CharField(max_length=255) 
    zone = models.CharField(max_length=255)
    # capacity = models.PositiveIntegerField(blank=True, null=True) # Kapasitas maksimum warehouse
    capacity = models.IntegerField(validators=[MinValueValidator(1)], blank=True, null=True)
    manager = models.CharField(max_length=255, blank=True, null=True)  # Nama manajer gudang
    current_inventory = models.PositiveIntegerField(default=0)  # Jumlah inventaris saat ini
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # active = models.BooleanField(default=True)
    address_line1 = models.CharField(max_length=255, blank=True, null=True, verbose_name='Alamat Baris 1')
    address_line2 = models.CharField(max_length=255, blank=True, null=True, verbose_name='Alamat Baris 2')
    province = models.ForeignKey(Provinsi, on_delete=models.CASCADE, blank=True, null=True)
    regency = models.ForeignKey(KabupatenKota, on_delete=models.CASCADE, blank=True, null=True)
    district = models.ForeignKey(Kecamatan, on_delete=models.CASCADE, blank=True, null=True)
    village = models.ForeignKey(KelurahanDesa, on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True, verbose_name='Alamat Email')
    phone_number = models.CharField(max_length=15, blank=True, null=True, validators=[RegexValidator(r'^\+?1?\d{9,15}$', "Phone number must be entered in the format: '+6281234567890'. Up to 15 digits allowed.")])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    # phone_number = PhoneNumberField(blank=True)
    def __str__(self):
        return f"{self.code} ({self.name})"
    
    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()
    
    class Meta:
        ordering = ['code']


class ProductCategory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # Unique identifier
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    def __str__(self):
        return self.name
    
    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()

    class Meta:
        ordering = ['name']


class ProductUOM(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=10)  # For example, kg, l, m
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    def __str__(self):
        return f"{self.code} ({self.name})"
    
    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()
    
    class Meta:
        ordering = ['code']
    
    
class ProductType(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True) 
    code = models.CharField(max_length=10)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    def __str__(self):
        return f"{self.code} ({self.name})"
    
    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()
    
    class Meta:
        ordering = ['code']
    
    
class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # Unique identifier
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    # price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    stock_quantity = models.PositiveIntegerField(default=0)
    # suppliers = models.ManyToManyField(Supplier, related_name='products')  # Many-to-many relationship
    uom = models.ForeignKey(ProductUOM, on_delete=models.CASCADE)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    sku = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE,)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    '''def generate_sku(self):
        """Generate a random SKU string of length 10 (you can adjust this length)."""
        return ''.join(random.choices('0123456789', k=10))  # Menghasilkan angka acak

    def save(self, *args, **kwargs):
        if not self.sku:  # Jika SKU tidak diisi, maka akan digenerate
            self.sku = self.generate_sku()

        super(Product, self).save(*args, **kwargs)'''

    def __str__(self):
        return f"{self.sku} ({self.name})"
    
    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()
    
    class Meta:
        ordering = ['sku']


class WarehouseProduct(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True) # Tracks soft delete timestamp

    def soft_delete(self):
        self.deleted_at = timezone.now()  # Set waktu penghapusan
        self.save()

    def restore(self):
        self.deleted_at = None  # Menghapus waktu penghapusan
        self.save()


class WarehouseStockProduct(models.Model):
    warehouse = models.ForeignKey(Warehouse, related_name='stocks', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='stocks', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)  # Menyimpan jumlah stok untuk setiap produk di warehouse
    
    def __str__(self):
        return f"Stock for {self.product.name} at {self.warehouse.name} - {self.quantity} units"


class StockAdjustment(models.Model):
    ADJUSTMENT_CHOICES = (
        ('increase', 'Increase'),
        ('decrease', 'Decrease'),
    )
    
    warehouse = models.ForeignKey(Warehouse, related_name='adjustments', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='adjustments', on_delete=models.CASCADE)
    adjustment_type = models.CharField(max_length=10, choices=ADJUSTMENT_CHOICES)
    quantity = models.IntegerField()  # Jumlah perubahan stok (positif atau negatif)
    reason = models.TextField(null=True, blank=True)  # Alasan penyesuaian stok (misalnya pengembalian, kerusakan)
    created_at = models.DateTimeField(default=timezone.now)
    
    def save(self, *args, **kwargs):
        # Mengambil stok produk yang bersangkutan di warehouse yang sesuai
        stock = WarehouseStockProduct.objects.get(warehouse=self.warehouse, product=self.product)
        
        # Saat penyesuaian stok dilakukan, update stok terkait
        if self.adjustment_type == 'increase':
            stock.quantity += self.quantity
        elif self.adjustment_type == 'decrease':
            stock.quantity -= self.quantity
        
        # Pastikan jumlah stok tidak kurang dari 0
        stock.quantity = max(stock.quantity, 0)
        
        stock.save()  # Simpan stok yang telah diupdate
        
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.adjustment_type.capitalize()} {self.quantity} units of {self.product.name} in {self.warehouse.name} for {self.reason}"

templates/core/pages/warehouse/create.html
{% extends 'core/layouts/base.html' %}
{% load static %}


{% block content %}
<!-- [ Main Content ] start -->
<div class="page-header">
    <h3 class="fw-bold mb-3">{{ title }}</h3>
    <!-- [ breadcrumb ] start -->
    {% block breadcrumbs %}
        {% include 'core/includes/breadcrumb.html' %}
    {% endblock breadcrumbs %}
    <!-- [ breadcrumb ] end -->
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Register</div>
            </div>
            <!-- <form class="needs-validation" novalidate> -->
            <form id="post-form" method="post" data-parsley-validate>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                        {% for field in form %}
                            {% if forloop.counter0|divisibleby:7 and not forloop.first %}
                                <!-- Start a new column for every second field -->
                                </div>
                                <div class="col-md-6">
                            {% endif %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% if field.name == 'province' %}
                                    {{ field.label_tag }}
                                    <select class="form-control form-select" 
                                            id="province" 
                                            name="{{ field.name }}"
                                            hx-get="{% url 'get_kabupaten_kota' %}" 
                                            hx-target="#regency-dropdown" 
                                            hx-trigger="change"
                                            >
                                        <option value="">Select Province</option>
                                        {% for provinsi in form.province.field.queryset %}
                                            <option value="{{ provinsi.id }}" {% if provinsi.id == form.instance.province.id %}selected{% endif %}>{{ provinsi.name }}</option>
                                        {% endfor %}
                                    </select>
                                {% elif field.name == 'regency' %}
                                    {{ field.label_tag }}
                                    <select class="form-control form-select" 
                                            id="regency-dropdown" 
                                            name="{{ field.name }}" 
                                            hx-get="{% url 'get_kecamatan' %}" 
                                            hx-target="#district-dropdown" 
                                            hx-trigger="change">
                                        <option value="">Select Regency/City</option>
                                    </select>
                                {% elif field.name == 'district' %}
                                    {{ field.label_tag }}
                                    <select class="form-control form-select" 
                                            id="district-dropdown" 
                                            name="{{ field.name }}" 
                                            hx-get="{% url 'get_kelurahan_desa' %}" 
                                            hx-target="#village-dropdown" 
                                            hx-trigger="change">
                                        <option value="">Select District</option>
                                    </select>
                                {% elif field.name == 'village' %}
                                    {{ field.label_tag }}
                                    <select class="form-control form-select" 
                                            id="village-dropdown" 
                                            name="{{ field.name }}">
                                        <option value="">Select Village/Subdistrict</option>
                                    </select>
                                {% else %}
                                    {{ field }}
                                {% endif %}

                                <!-- If there are errors for this field, display them -->
                                {% if field.errors %}
                                    <div><small class="form-text text-danger">{{ field.errors.0 }}</small></div>
                                {% endif %}
        
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="card-action">
                    <button type="button" class="btn btn-success" id="confirm">Submit</button>	
                    <button class="btn btn-primary" type="button" onclick="window.history.back();">Back</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
{% endblock content %}

templates/core/pages/warehouse/detail.html
{% extends 'core/layouts/base.html' %}
{% load static custom_filters %}

{% block content %}
<!-- [ Main Content ] start -->
<div class="page-header">
    <h3 class="fw-bold mb-3">{{ title }}</h3>
    <!-- [ breadcrumb ] start -->
    {% block breadcrumbs %}
        {% include 'core/includes/breadcrumb.html' %}
    {% endblock breadcrumbs %}
    <!-- [ breadcrumb ] end -->
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center">
                    <h4 class="card-title">Detail</h4>
                    <button class="btn btn-primary btn-round ms-auto me-1" onclick="window.location.href='{% url 'warehouse_create' %}'">
                        <i class="fa fa-plus"></i>
                        Register
                    </button>
                    <form id="post-form" method="post" action="{% url 'warehouse_delete' pk=item.id %}">
                        {% csrf_token %}
                        {{ button_delete|safe }}
                    </form>
                </div>
            </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                        {% for field in form %}
                            {% if forloop.counter0|divisibleby:7 and not forloop.first %}
                                <!-- Start a new column for every second field -->
                                </div>
                                <div class="col-md-6">
                            {% endif %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% if field.name == "regency" %}
                                    <!-- Read-only input for regency -->
                                    <input type="text" name="regency" id="id_regency" class="form-control" value="{{ object.regency.name }}" readonly>
                                {% elif field.name == "district" %}
                                    <!-- Read-only input for district -->
                                    <input type="text" name="district" id="id_district" class="form-control" value="{{ object.district.name }}" readonly>
                                {% elif field.name == "village" %}
                                    <!-- Read-only input for village -->
                                    <input type="text" name="village" id="id_village" class="form-control" value="{{ object.village.name }}" readonly>
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            <div class="card-action">
                <button class="btn btn-warning" onclick="window.location.href='{% url 'warehouse_update' pk=object.id %}'">Edit</button>
                <button class="btn btn-primary" type="button" onclick="window.history.back();">Back</button>
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
{% endblock content %}

templates/core/pages/warehouse/list.html
{% extends 'core/layouts/base.html' %}
{% load static custom_filters %}


{% block content %}
<!-- [ Main Content ] start -->
<div class="page-header">
    <h3 class="fw-bold mb-3">{{ title }}</h3>
    <!-- [ breadcrumb ] start -->
    {% block breadcrumbs %}
        {% include 'core/includes/breadcrumb.html' %}
    {% endblock breadcrumbs %}
    <!-- [ breadcrumb ] end -->
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center">
                    <h4 class="card-title">List</h4>
                    <button class="btn btn-primary btn-round ms-auto" onclick="window.location.href='{% url 'warehouse_create' %}'">
                        <i class="fa fa-plus"></i>
                        Register
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="multi-filter-select" class="display table table-hover" >
                        <thead>
                            <tr class="table-secondary">
                              <th class="mw-25">#</th>
                              {% for key, value in fields.items %}
                                <th>{{ value }}</th>
                              {% endfor %}
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                            <th class="mw-25">#</th>
                            {% for key, value in fields.items %}
                                <th>{{ value }}</th>
                            {% endfor %}
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for item in list_item %}
                            <tr class="pe-auto {{ class_color }}" onclick="window.location.href='{% url 'warehouse_detail' pk=item.id %}'" style="cursor: pointer;">
                              <td>{{ forloop.counter }}</td>
                              {% for field in fields %}
                                <td>{{ item|get_field_value:field }}</td>
                              {% endfor %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% block filter_buttons %}
            {% include 'core/includes/filter_buttons.html' %}
        {% endblock %}
    </div>
</div>
<!-- [ Main Content ] end -->
{% endblock content %}

templates/core/pages/warehouse/update.html
{% extends 'core/layouts/base.html' %}
{% load static %}

{% block content %}
<!-- [ Main Content ] start -->
<div class="page-header">
    <h3 class="fw-bold mb-3">{{ title }}</h3>
    <!-- [ breadcrumb ] start -->
    {% block breadcrumbs %}
        {% include 'core/includes/breadcrumb.html' %}
    {% endblock breadcrumbs %}
    <!-- [ breadcrumb ] end -->
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="d-flex align-items-center">
                    <h4 class="card-title">Edit</h4>
                    <button class="btn btn-primary btn-round ms-auto" onclick="window.location.href='{% url 'warehouse_create' %}'">
                        <i class="fa fa-plus"></i>
                        Register
                    </button> 
                </div>
            </div>
                <!-- <form class="needs-validation" novalidate> -->
                <form id="post-form" method="post" data-parsley-validate>
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                            {% for field in form %}
                                {% if forloop.counter0|divisibleby:7 and not forloop.first %}
                                    <!-- Start a new column for every second field -->
                                    </div>
                                    <div class="col-md-6">
                                {% endif %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {% if field.name == 'province' %}
                                        {{ field.label_tag }}
                                        <select class="form-control form-select"
                                            id="province" 
                                            name="{{ field.name }}"
                                            hx-get="{% url 'get_kabupaten_kota' %}" 
                                            hx-target="#regency-dropdown" 
                                            hx-trigger="change">
                                            <option value="">Select Province</option>
                                            {% for provinsi in form.province.field.queryset %}
                                                <option value="{{ provinsi.id }}" {% if provinsi.id == form.instance.province.id %}selected{% endif %}>{{ provinsi.name }}</option>
                                            {% endfor %}
                                        </select>

                                    {% elif field.name == 'regency' %}
                                        {{ field.label_tag }}
                                        <select class="form-control form-select" 
                                            id="regency-dropdown" 
                                            name="{{ field.name }}" 
                                            hx-get="{% url 'get_kecamatan' %}" 
                                            hx-target="#district-dropdown" 
                                            hx-trigger="change">
                                            <option value="">Select Regency/City</option>
                                            {% for regency in form.regency.field.queryset %}
                                                <option value="{{ regency.id }}" {% if regency.id == form.instance.regency.id %}selected{% endif %}>{{ regency.name }}</option>
                                            {% endfor %}
                                        </select>

                                    {% elif field.name == 'district' %}
                                        {{ field.label_tag }}
                                        <select class="form-control form-select" 
                                            id="district-dropdown" 
                                            name="{{ field.name }}" 
                                            hx-get="{% url 'get_kelurahan_desa' %}" 
                                            hx-target="#village-dropdown" 
                                            hx-trigger="change">
                                            <option value="">Select District</option>
                                            {% for district in form.district.field.queryset %}
                                                <option value="{{ district.id }}" {% if district.id == form.instance.district.id %}selected{% endif %}>{{ district.name }}</option>
                                            {% endfor %}
                                        </select>

                                    {% elif field.name == 'village' %}
                                        {{ field.label_tag }}
                                        <select class="form-control form-select" 
                                            id="village-dropdown" 
                                            name="{{ field.name }}">
                                            <option value="">Select Village/Subdistrict</option>
                                            {% for village in form.village.field.queryset %}
                                                <option value="{{ village.id }}" {% if village.id == form.instance.village.id %}selected{% endif %}>{{ village.name }}, {{ village.postal_code }}</option>
                                            {% endfor %}
                                        </select>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}

                                    <!-- If there are errors for this field, display them -->
                                    {% if field.errors %}
                                    <div><small class="form-text text-danger">{{ field.errors.0 }}</small></div>
                                    {% endif %}


                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}

                                </div>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                <div class="card-action">
                    <button type="button" class="btn btn-success" id="confirm">Submit</button>	
                    <button class="btn btn-primary" type="button" onclick="window.history.back();">Back</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
{% endblock content %}